### ISSUE TITLE
Duplication of vegetables

### ISSUE THREAD

**Issue by Johandrex** [shansen/EggCatcher#8]
When throwing a egg on villagers tons of carrots/potatoes etc are flying up from the ground for some reason - https://www.youtube.com/watch?v=HC0izaaVC8k&feature=youtu.be

**Comment by Johandrex** [comment]
Version 2.4

**Comment by shansen** [comment]
Thanks for reporting this. I checked it and it's just the inventory of the villager that gets dropped. If you look carefully in your video you'll see the first villager you catch, drops his carrots on the ground. The 2nd villager picks them up before you get there and then drops them with his own inventory of carrots when you catch him with the egg.

EggCatcher drops all mobs inventory per default. So you can basically respawn the villager and give it it's carrots back. It's also there to make sure zombies and so on drops whatever they pick up.

For villagers it could be used to set up some interesting automatic farms. But I can also see that some servers might find this undesirable. I'll probably put it in as an option in the configuration file.

**Comment by Johandrex** [comment]
Ahh I see. Please add it as option to disable though ;)

**Comment by shansen** [comment]
Added DeleteVillagerInventoryOnCatch option in version 2.5 which was just uploaded to dev.bukkit.org and spigotmc.org
