### ISSUE TITLE
Plugin doesn't catch Undead Horses

### ISSUE THREAD

**Issue by DrkMatr1984** [shansen/EggCatcher#9]
I use a plugin to naturally spawn undead horses and ride them on my server. I noticed the eggs won't catch them. Could you add support for these types into mainstream eggcatcher? Thanks!

**Comment by shansen** [comment]
Hi,
Sorry for the late reply, I didn't get notified.
Unfortunately I can't replicate this. I am able to catch undead horses without a problem. Do you still have this problem?

**Comment by DrkMatr1984** [comment]
Not sure, I will check and get back to you!

**Comment by shansen** [comment]
I'm closing this as I'm assuming this is no longer a problem. You are welcome to reopen if you still have problems :)
